# Generated by Django 3.0.2 on 2020-02-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('massmailer', '0001_initial')]

    operations = [
        migrations.RemoveField(model_name='batchemail', name='user'),
        migrations.AddField(
            model_name='batchemail',
            name='unsubscribe_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='template',
            name='is_marketing',
            field=models.BooleanField(
                default=False,
                help_text='Adds an Unsubscribe header and makes sure the email contains the unsubscribe URL.',
                verbose_name='This is a ‘marketing’ email',
            ),
        ),
    ]
