# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=144)),
                ('description', models.TextField(blank=True)),
                ('query', models.TextField()),
            ],
            options={
                'verbose_name': 'Query',
                'verbose_name_plural': 'Queries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=144, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('subject', models.TextField(verbose_name='Subject template')),
                ('plain_body', models.TextField(verbose_name='Plaintext body template')),
                ('html_body', models.TextField(blank=True, verbose_name='HTML body template')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='query',
            name='useful_with',
            field=models.ManyToManyField(related_name='useful_queries', blank=True, to='mailing.Template'),
        ),
    ]
